-- AlterEnum
ALTER TYPE "WorkspaceProduct" ADD VALUE IF NOT EXISTS 'TASKS';
ALTER TYPE "WorkspaceProduct" ADD VALUE IF NOT EXISTS 'HRMS';
ALTER TYPE "WorkspaceProduct" ADD VALUE IF NOT EXISTS 'BCI';
ALTER TYPE "WorkspaceProduct" ADD VALUE IF NOT EXISTS 'CRM';
