-- AlterEnum
ALTER TYPE "InboundLeadStatus" ADD VALUE IF NOT EXISTS 'DEMO_SCHEDULED';
ALTER TYPE "InboundLeadStatus" ADD VALUE IF NOT EXISTS 'NEGOTIATION';

-- AlterTable
ALTER TABLE "InboundLead" ADD COLUMN IF NOT EXISTS "expectedCloseAt" TIMESTAMP(3);
ALTER TABLE "InboundLead" ADD COLUMN IF NOT EXISTS "winProbability" INTEGER;
