export const PRODUCT = {
  name: "Petal",
  hindi: "पेटल",
  hinglish: "Aadhi Raat me pani pila du",
  legal: "Surya Mineral",
  email: "accounts@petal.local",
  hours: "Mon–Sat · 10am–7pm IST",
};

export const TENANT = {
  slug: "petal",
  name: "Petal",
  legal: "Surya Mineral",
  owner: "Shashi Bhushan Patel",
  phone: "+91 87707 73556",
  tel: "+918770773556",
  pinOwner: "1234",
  pinStaff: "0000",
};

export const BRAND = {
  name: PRODUCT.name,
  legal: PRODUCT.legal,
  owner: TENANT.owner,
  hindi: PRODUCT.hindi,
  hinglish: PRODUCT.hinglish,
  phone: TENANT.phone,
  tel: TENANT.tel,
  email: PRODUCT.email,
  hours: PRODUCT.hours,
  city: "India",
  pinOwner: TENANT.pinOwner,
  pinStaff: TENANT.pinStaff,
};

export const MAX_USERS = 5;

export const LANGS = ["English", "हिन्दी", "मराठी", "தமிழ்", "తెలుగు", "বাংলা", "ગુજરાતી", "ਪੰਜਾਬੀ"] as const;

export const COPY = {
  en: {
    overline: "Water delivery business app",
    hero1: "Run your",
    heroEm: "jar water",
    hero2: "business from your pocket.",
    sub: "One store. Five users. Daily jar deliveries, monthly bills like Craffle, empties, cash/UPI, and expenses — raw material, labour, salary, petrol, diesel.",
    features: "Features",
    how: "How it works",
    pricing: "Pricing",
    customers: "Customers",
    faq: "FAQ",
    bizLogin: "Business Login",
    custLogin: "Customer Login",
    demo: "Open live demo",
  },
  hi: {
    overline: "पानी डिलीवरी बिज़नेस ऐप",
    hero1: "अपना",
    heroEm: "जार पानी",
    hero2: "का धंधा जेब से चलाओ.",
    sub: "एक स्टोर. पाँच यूज़र. रोज़ जार, महीना बिल, खाली जार, कैश/UPI, और खर्च — कच्चा माल, लेबर, सैलरी, पेट्रोल, डीजल.",
    features: "फीचर",
    how: "कैसे काम करता है",
    pricing: "प्राइस",
    customers: "ग्राहक",
    faq: "सवाल",
    bizLogin: "एजेंसी लॉगिन",
    custLogin: "कस्टमर लॉगिन",
    demo: "लाइव डेमो खोलो",
  },
} as const;

export const APP = {
  en: {
    home: "Home",
    deliveries: "Deliveries",
    customers: "Customers",
    products: "Products",
    invoices: "Invoices",
    payments: "Payments",
    stock: "Stock",
    staff: "Staff",
    routes: "Routes",
    subs: "Subscriptions",
    events: "Events",
    store: "Storefront",
    reports: "Reports",
    settings: "Settings",
    expenses: "Expenses",
    more: "More",
    driver: "Driver",
    out: "Sign out",
    bulk: "Deliver all pending",
    wa: "Print bill",
    import: "Import CSV",
  },
  hi: {
    home: "होम",
    deliveries: "डिलीवरी",
    customers: "ग्राहक",
    products: "प्रोडक्ट",
    invoices: "बिल",
    payments: "पेमेंट",
    stock: "स्टॉक",
    staff: "स्टाफ",
    routes: "रूट",
    subs: "सब्सक्रिप्शन",
    events: "इवेंट",
    store: "स्टोर",
    reports: "रिपोर्ट",
    settings: "सेटिंग",
    expenses: "खर्च",
    more: "और",
    driver: "ड्राइवर",
    out: "साइन आउट",
    bulk: "बाकी डिलीवर",
    wa: "बिल प्रिंट",
    import: "CSV",
  },
} as const;
