import {
  learnPracticeWorkbookUrl,
  type PracticeTabName,
} from "@/lib/learn/practice-workbook";

export type SheetsTeachingPack = {
  no: number;
  tab: PracticeTabName | null;
  goal: string;
  practicePrompt: string;
  bodyMd: string;
  embedUrl: string;
};

function unhide(tab: string) {
  return `File → Make a copy of the practice workbook. Bottom tab bar → right-click any tab → Unhide → open **${tab}**.`;
}

function pack(
  no: number,
  tab: PracticeTabName | null,
  goal: string,
  practicePrompt: string,
  bodyMd: string,
): SheetsTeachingPack {
  return {
    no,
    tab,
    goal,
    practicePrompt,
    bodyMd,
    embedUrl: learnPracticeWorkbookUrl(),
  };
}

export const SHEETS_TEACHING: SheetsTeachingPack[] = [
  pack(
    1,
    "Google Sheets Session",
    "You can read the TOC and know which hidden practice tab belongs to today's session.",
    `${unhide("Google Sheets Session")} This is the TOC. Column C is the session. Hidden tabs are the practice sheets. Do not edit the TOC except Status after class.`,
    "This file is one course, not 58 demo files. TOC on Google Sheets Session. Practice lives on hidden tabs so the student is not lost in 40 sheets on day one.\n\nRawData is the fat sales dump the later tabs read: Key, OrderDate, Region, Sales Person, Item, Units, Unit Cost, Total. Stationery — Desk, Pencil, Binder, Pen, Pen Set. Regions Central / East / West.\n\nUnhide only the tab for this session. Hide it again when you leave.",
  ),
  pack(
    2,
    "Google Sheets Session",
    "You can start a clean spreadsheet, name it, and keep the TOC file as the master.",
    `${unhide("Google Sheets Session")} File → Make a copy. Rename it Sheets-Practice-YourName. Do not work in the shared master.`,
    "First job is a named copy. The master stays clean for the next student. Tab names stay as they are — VLOOKUP, Query, RawData — so class instructions still match.",
  ),
  pack(
    3,
    "Data Clean Up",
    "You can bring a CSV / Excel dump in without shifting RawData columns.",
    `${unhide("Data Clean Up")} This is how a dump looks after import — Central. vs Central, Ashish. vs Ashish. File → Import only onto a scratch tab, never onto RawData.`,
    "RawData is the clean grain. Data Clean Up is the messy twin. Import → Replace that tab only. Check Units stayed numbers. If Sheets ate a leading 0 on a code, the column was formatted as number.",
  ),
  pack(
    4,
    "Google Sheets Session",
    "You can send a PDF of one tab and an Excel copy without dumping every hidden sheet.",
    `${unhide("Google Sheets Session")} File → Download → PDF (current sheet = TOC). Then Download → Excel. Open Excel and see hidden tabs came along — that is why we PDF one sheet for a client.`,
    "Owner wants PDF. Student wants Excel. PDF the tab you are on. Excel is the whole workbook including hidden practice tabs — fine for homework, messy for a client WhatsApp.",
  ),
  pack(
    5,
    "Google Sheets Session",
    "You can publish one tab as a webpage and keep the rest private.",
    `${unhide("Google Sheets Session")} File → Share → Publish to web → this TOC tab only. Do not publish RawData.`,
    "Publishing the whole file is how a rate list leaks. Publish one tab. Unpublish when the link should die.",
  ),
  pack(
    6,
    "DATE functions",
    "You can move and stamp dates from the keyboard.",
    `${unhide("DATE functions")} Row 3 is the shortcut: Shift + Ctrl + ; for date, Shift + Ctrl + Shift + : for time. Then fill TODAY / NOW / DAY / MONTH / YEAR on the OrderDate column.`,
    "Shortcuts are how we move in RawData. The DATE tab prints the stamp keys at the top so you do not hunt the menu.",
  ),
  pack(
    7,
    "Hide | Group",
    "You can hide a column and get it back — never delete.",
    `${unhide("Hide | Group")} Hide Sales Person. Unhide it. Group Region + Item. The help link on the tab is the official Hide/group article.`,
    "Hidden is not deleted. Deleted columns break the next VLOOKUP. Same idea as the hidden practice tabs on this file.",
  ),
  pack(
    8,
    "Protect | Lock",
    "You can lock a range so a classmate cannot overwrite the UID.",
    `${unhide("Protect | Lock")} Data → Protect sheets and ranges on column A (UID). Leave the rest open. Open the help link on the tab.`,
    "Protect the key. RawData keys are IDSGS1123… If someone types over a key, every lookup on VLOOKUP / IndexMatch dies.",
  ),
  pack(
    9,
    "Filter | Filter View",
    "You can filter West without changing the sheet for the room.",
    `${unhide("Filter | Filter View")} Data → Filter views → Create. Name it West-Ramesh. Filter Region=West and Sales Person=Ramesh. Close the view. The main sheet must look unchanged.`,
    "The green Filter changes the file for everyone. Filter view is yours. This tab is a copy of RawData so you can practise without touching the source.",
  ),
  pack(
    10,
    "Data Clean Up",
    "You can clean Central. and Ashish. without rewriting 1,000 rows by hand.",
    `${unhide("Data Clean Up")} Find Central. and Ashish. (trailing dot). Data → Data cleanup → Cleanup suggestions. Accept only trailing spaces/dots. Do not merge names.`,
    "This tab is the dirty twin of RawData. Cleanup suggestions will happily merge two people. I accept spaces and dots. Then TRIM on a helper if anything is left.",
  ),
  pack(
    11,
    "Data Validation | Drop Downs",
    "You can force Sales Person and country code to a list.",
    `${unhide("Data Validation | Drop Downs")} Column B Sales Person: Data → Validation → list from Setting (Shyam, Mohd. Hilal, Rajesh, Rakesh). Try a name that is not on the list — it should reject.`,
    "Setting is the list the dropdown reads. Same pattern later for Depended Drop Down. Validation is cheaper than fixing 200 rows of 'paid ' vs Paid.",
  ),
  pack(
    12,
    "Google Sheets Session",
    "You get a mail when someone edits RawData after hours.",
    `${unhide("Google Sheets Session")} Tools → Notification rules → RawData → any change → daily digest. Not instant, or you will mute it.`,
    "Instant mail on a 1,000-row dump is noise. Daily digest. Turn rules off before a bulk import.",
  ),
  pack(
    13,
    "RawData",
    "You can argue on a cell without overwriting the number.",
    `${unhide("RawData")} On the first Desk row, Insert → Comment: 'Keep Unit Cost 2. Special rate only on the bill.' Resolve after you read it.`,
    "Notes print. Comments are the conversation. Do not type the discussion into Unit Cost.",
  ),
  pack(
    14,
    null,
    "You know what still works when the line is down.",
    "File → Make a copy. Enable offline on this Google account. Open the copy once online. Airplane mode. Edit one cell on your copy. GOOGLEFINANCE and IMPORTRANGE will not refresh offline.",
    "Billing can go offline. Google Finance and Importrange wait for the line. That is why those sit on their own tabs.",
  ),
  pack(
    15,
    "Google Sheets Session",
    "You can share the copy as Viewer and keep the master locked.",
    `${unhide("Google Sheets Session")} Share your copy: Viewer for a dummy mail. Confirm they can see TOC and cannot edit RawData if you also protect it.`,
    "Anyone-with-link editor is how the file dies. Viewer on the homework copy. You stay editor.",
  ),
  pack(
    16,
    "CONCATENATE | TEXT_JOIN",
    "You can build a full name with & and TEXTJOIN.",
    `${unhide("CONCATENATE | TEXT_JOIN")} Column C is CONCATENATE. Column D is A&\" \"&B. Top row TEXTJOIN across G:Q. Write one more name at the bottom both ways.`,
    "CONCATENATE is old. & is what I type live. TEXTJOIN when a middle name might be blank and you do not want leftover spaces.",
  ),
  pack(
    17,
    "COUNTS",
    "You can tell COUNT, COUNTA, and COUNTBLANK apart on a mixed column.",
    `${unhide("COUNTS")} Row 19 already has =COUNT(B2:B18), COUNTA(C2:C18), COUNTBLANK(D2:D18). Write why C has more than B (text + numbers vs numbers only).`,
    "COUNT = numbers only. COUNTA = anything filled. COUNTBLANK = holes. If you COUNT a name column you get 0 and think the list is empty.",
  ),
  pack(
    18,
    "LEN | TRIM",
    "You can see extra spaces with LEN before they break a lookup.",
    `${unhide("LEN | TRIM")} 'Google   ' is 6 visible letters and a longer LEN. Write =LEN(A5) and =LEN(TRIM(A5)). Same for the TRIM block at row 14.`,
    "LEN is the check. TRIM is the fix. Do TRIM on a helper, paste values, then lookup.",
  ),
  pack(
    19,
    "LEN | TRIM",
    "You can strip leading and trailing spaces.",
    `${unhide("LEN | TRIM")} The TRIM block: =TRIM(A14) next to =LEN(A14). Fill the second example. Paste values if you want the clean text to stay.`,
    "VLOOKUP does not forgive a trailing space. This tab is the first formula I write on any dump.",
  ),
  pack(
    20,
    "SUBSTITUTE|L|U|P",
    "You can turn amar@asutosh into a name and strip junk characters.",
    `${unhide("SUBSTITUTE|L|U|P")} Column B SUBSTITUTE @ for a space. Then LOWER / UPPER / PROPER. Read the syntax note on the tab.`,
    "Tally and WhatsApp dumps mix @ . _ %. SUBSTITUTE one mark. REGEXREPLACE if there are many. Do not PROPER an email.",
  ),
  pack(
    21,
    "SUBSTITUTE|L|U|P",
    "You can standardise case without ruining codes.",
    `${unhide("SUBSTITUTE|L|U|P")} UPPER the full name. PROPER the full name. See that PROPER is for people, not IDs like MOD-609.`,
    "PROPER on a SKU makes Mcb and Gstin. Names yes. Item codes no.",
  ),
  pack(
    22,
    "DATE functions",
    "You can put today's date in a cell without typing it.",
    `${unhide("DATE functions")} Column B =TODAY() next to OrderDate. Change nothing else. The date must move tomorrow.`,
    "If you type the date, the file is stale tomorrow. TODAY() is the clock this tab uses with DAY / MONTH / YEAR.",
  ),
  pack(
    23,
    "DATE functions",
    "You know NOW() keeps moving and when to paste values.",
    `${unhide("DATE functions")} Column C =NOW(). Watch the time change on recalc. Say out loud why we do not use NOW as an audit log.`,
    "NOW is live. Good for 'as of'. Bad for a log. Paste values if you need a stamp that stays.",
  ),
  pack(
    24,
    "DATE functions",
    "You can pull day, month, year and build the date back.",
    `${unhide("DATE functions")} On the first OrderDate: DAY, MONTH, YEAR, then =DATE(year, month, day). It must match the original date.`,
    "DATE(F,E,D) is how we rebuild a period. This is the grain later QUERY and pivots use.",
  ),
  pack(
    25,
    "DATEDIF | EOMONTH",
    "You can age a start date to today in days.",
    `${unhide("DATEDIF | EOMONTH")} =DATEDIF(A5,B5,\"D\") next to B5-A5. Same answer. Then EOMONTH on the right block.`,
    "DATEDIF is the old one Sheets still uses for D / M / Y. DAYS or minus is cleaner for bill ageing. I show both so an old CA file does not scare you.",
  ),
  pack(
    26,
    "DATEDIF | EOMONTH",
    "You can take a simple day difference and month-end.",
    `${unhide("DATEDIF | EOMONTH")} B5-A5 is the simple DAYS idea. EOMONTH(F5,G5) jumps month-ends — useful for credit cycles.`,
    "Minus two dates = days. EOMONTH is 'last day of this month plus N months'. That is a statement date, not a birthday.",
  ),
  pack(
    27,
    "Conditional Formatting",
    "You can colour ageing buckets without painting cells by hand.",
    `${unhide("Conditional Formatting")} Days = TODAY()-OrderDate. Rules on the tab: <90, 90-120, >120, plus a colour scale. Add one more row and watch the colour follow.`,
    "Do not colour by hand. Next import wipes it. Rule on the whole Days column. Three colours. Advanced Conditional Formatting is the Gantt extra if they finish early.",
  ),
  pack(
    28,
    "RawData",
    "You can copy a practice tab into a new spreadsheet.",
    `${unhide("RawData")} Right-click RawData → Copy to → New spreadsheet. Name it RawData-Master. That is how a template leaves the course file.`,
    "Each new client gets a copy of the grain, not a retype. Copy to existing spreadsheet when they already have a file and you are only giving them the dump.",
  ),
  pack(
    29,
    "RawData",
    "You can treat RawData as a table: freeze header, named range, sort without losing the header.",
    `${unhide("RawData")} Freeze row 1. Bold the header. Data → Named ranges → SalesData = RawData!A1:H. Sort by OrderDate. Header must stay.`,
    "Sheets is not Excel Tables. Freeze + named range is what QUERY, FILTER, and pivots eat. If the header sorts into row 40, the class failed.",
  ),
  pack(
    30,
    "Split | Index",
    "You can split an email and pick the first name.",
    `${unhide("Split | Index")} =SPLIT(A2,\"@\") then INDEX on the name side with \".\". Write one more email at the bottom. Open the help links on the tab.`,
    "WhatsApp and mail dumps arrive as one cell. SPLIT makes columns. INDEX picks the nth piece when you do not want all of them.",
  ),
  pack(
    31,
    "VLOOKUP",
    "You can pull OrderDate / person / item / region from RawData with a Key.",
    `${unhide("VLOOKUP")} Keys are already listed (IDSGS1127…). Write VLOOKUP(A2, RawData!A:H, 2, FALSE) for OrderDate. FALSE. Then fill Item and Region.`,
    "This is the spine. RawData is the table. Key is the search. Column index is 1-based. Approximate match has no place on a key like IDSGS1127.",
  ),
  pack(
    32,
    "Hlookup",
    "You can read a field across a header row.",
    `${unhide("Hlookup")} The top block is RawData flipped. Cell E13 is a Key. =HLOOKUP(E13,1:8,3) should return that key's Region. Then try row 4 for Sales Person.`,
    "HLOOKUP reads a header row. Rate lists grow down, not across. I teach it so an old CA file does not trap you. Then we go back to VLOOKUP / XLOOKUP.",
  ),
  pack(
    33,
    "VLOOKUP",
    "You can try a wildcard when the key is not exact — and see why it is dangerous.",
    `${unhide("VLOOKUP")} Try VLOOKUP(\"*1128*\", RawData!A:H, 5, FALSE). If two keys match, you get the first. That is why we still fix the Key.`,
    "Wildcard is a last resort. Better to clean the Key. Two matches = wrong region on the bill.",
  ),
  pack(
    34,
    "Index + Match",
    "You can look up a Key when the return column is to the left of the search.",
    `${unhide("Index + Match")} INDEX + MATCH on the first UID. Then open IndexMatch — same idea, second example. MATCH must be 0.`,
    "VLOOKUP cannot look left. INDEX/MATCH can. Two tabs so we can fail on one and still have a clean drill.",
  ),
  pack(
    35,
    "XLOOKUP",
    "You can write XLOOKUP in English: find this ID, return Item.",
    `${unhide("XLOOKUP")} Search the ID, return Item from RawData. If missing, return NO KEY. Open the help link on the tab.`,
    "XLOOKUP looks left, can return a blank instead of #N/A, and reads in English. Old Excel on a CA laptop may not have it — then VLOOKUP.",
  ),
  pack(
    36,
    "Arrayformula + Vlookup",
    "You can fill a column with one ARRAYFORMULA + VLOOKUP.",
    `${unhide("Arrayformula + Vlookup")} One ARRAYFORMULA that looks up Item for every UID in column A. Add a UID at the bottom — Item should appear without a drag.`,
    "If they drag 1,000 rows, next week's keys are blank and they say Sheets is broken. ARRAYFORMULA is the system layer.",
  ),
  pack(
    37,
    "Importrange + Vlookup",
    "You can pull a price from another workbook and VLOOKUP it.",
    `${unhide("Importrange + Vlookup")} Row 1 has IMPORTRANGE help + the source file. Allow access. Column G is ARRAYFORMULA(VLOOKUP(…IMPORTRANGE…)). Until access is granted you will see #REF!.`,
    "Two files is the honest shop. IMPORTRANGE is the pipe. First time Sheets asks permission. If it dies later, someone renamed the tab.",
  ),
  pack(
    38,
    "Filter",
    "You can make a live list from RawData without a pivot.",
    `${unhide("Filter")} C1 / G1 drive Region and Sales Person. The FILTER reads RawData. Change West → East and watch the list rebuild. Sheet20 is FILTER for Yogesh only.`,
    "FILTER is the shop floor. Pivot is the meeting. If they copy-paste the result, it is dead tomorrow. Leave the formula.",
  ),
  pack(
    39,
    "Depended Drop Down",
    "You can make Category change when Use Case changes.",
    `${unhide("Depended Drop Down")} Lists are Use Case → Category → Subcategory (Travel, Asset, Purchase). Data → Validation on a helper: L2 filters on L1. Pick Travel Reimbursement, then only Domestic / International.`,
    "Dependent dropdown is how a form stops the wrong city on an invoice. First unique list. Second FILTER on that pick. Setting is the simple one-level list.",
  ),
  pack(
    40,
    "Query",
    "You can write a QUERY like a small SQL on RawData.",
    `${unhide("Query Basics")} The header says QUERY FUNCTION. It selects from RawData with a where on Region. Then open Query — C1 / G1 are the criteria (Central, Richard). Change them. Sheet22 is select C, sum(H) group by C.`,
    "QUERY is the analyst tab. Basics = one select. Query = criteria cells. Sheet22 = group by Region. If it errors, you dropped a quote.",
  ),
  pack(
    41,
    "Error Handeling",
    "You can hide #N/A on a missing Key without hiding a real typo.",
    `${unhide("Error Handeling")} Wrap the lookup with IFNA(...,\"NO KEY\"). IFERROR only if divide-by-zero is possible. The tab name is spelled Handeling — that is the file, do not rename it.`,
    "A client-facing #N/A looks like the file is broken. IFERROR hides everything. I prefer IFNA on lookups.",
  ),
  pack(
    42,
    "AND | OR (IF(AND(OR))",
    "You can flag a row if any of the chase rules match.",
    `${unhide("AND | OR (IF(AND(OR))")} Read the header: Central|East / Desk / Units>100. Column for OR: Region is Central or East. Filter TRUE.`,
    "OR is the follow-up pile. Not only one city. Keep it boring and visible.",
  ),
  pack(
    43,
    "AND | OR (IF(AND(OR))",
    "You can flag a row only if every condition matches.",
    `${unhide("AND | OR (IF(AND(OR))")} H5 is already IF(AND(Region=Central, Item=Desk, Units>100),\"Champ!\",\"try next time\"). Fill it down. Almost no row is Champ — that is the point.`,
    "AND is a tight rule. City and item and qty. This is how a sheet becomes a system instead of a dump.",
  ),
  pack(
    44,
    "IF Statements",
    "You can bucket ageing with IF.",
    `${unhide("IF Statements")} Days till Date = TODAY()-OrderDate. Column C is nested IF slabs. Read one row out loud. Then look at column D — IFS does the same job.`,
    "IF is the alarm. One condition first. When they nest five IFs I stop them and we write IFS.",
  ),
  pack(
    45,
    "IF Statements",
    "You can replace nested IF with IFS.",
    `${unhide("IF Statements")} Column D is IFS into the slab labels on the right (<30, 30-60, … >150). Add a 180+ label and point the last IFS there.`,
    "IFS reads top to bottom. First true wins. Put the tight buckets first.",
  ),
  pack(
    46,
    "AND | OR (IF(AND(OR))",
    "You can combine IF with AND / OR without twisting the file.",
    `${unhide("AND | OR (IF(AND(OR))")} Write IF(OR(...),\"CHASE\",\"ok\") on a helper using the header rules. If it feels twisted, split into helper columns.`,
    "I allow one nested line. After that, helper columns. The owner must read it next April.",
  ),
  pack(
    47,
    "Sumif",
    "You can total RawData by Region and by person.",
    `${unhide("Sumif")} SUMIF Region (Central / East / West) on Total. Then the Sales Person block. Open Sumifs for person × region. Help link is on the tab.`,
    "SUMIF is one condition. SUMIFS is the meeting table. If the number is wrong, check spelling — Central vs Central.",
  ),
  pack(
    48,
    "Countif",
    "You can count bills by Region, person, and item.",
    `${unhide("Countif")} COUNTIF RawData!C:C for Central / East / West. Then the person and item blocks. Countifs is the grid: person × Central/East/West.`,
    "COUNTIF is how many. SUMIF is how much. Owners mix the two and fight. Write both, labelled.",
  ),
  pack(
    49,
    "Google Finance",
    "You can pull a live price and USDINR without putting it on RawData.",
    `${unhide("Google Finance")} Row 1 is the syntax. Right side is the use-case list (price, volume, PE, currency). Write =GOOGLEFINANCE(\"CURRENCY:USDINR\") on a blank cell. Needs internet.`,
    "Do not put GOOGLEFINANCE on RawData. Offline billing must still work. This tab is the market check.",
  ),
  pack(
    50,
    "Sparkline",
    "You can put a bar in the row so Actual vs Target is obvious.",
    `${unhide("Sparkline")} Actual / Target / Threshold / Difference / Bar. Change Desk Actual from 80 to 95 and watch the bar. charttype is bar.`,
    "SPARKLINE is the cheap chart inside the table. If Target is 0 the bar vanishes.",
  ),
  pack(
    51,
    "Pivot Table | Slicers",
    "You can build City/Region × Item from RawData.",
    `${unhide("Pivot Table | Slicers")} Insert → Pivot table from RawData A:H. Rows Region, Columns Item, Values SUM of Total. One question per pivot.`,
    "I never pivot a pretty layout first. RawData is the grain. Region × Item is the territory meeting.",
  ),
  pack(
    52,
    "Pivot Table | Slicers",
    "You can add a calculated field on the pivot.",
    `${unhide("Pivot Table | Slicers")} On the Region × Item pivot add a calculated field if you have Units and Total — average rate = Total / Units. Name it, do not leave Calc1.`,
    "Taxable is vanity. A named calculated field is how you say that in the meeting without a second sheet.",
  ),
  pack(
    53,
    "Pivot Table | Slicers",
    "You can chart the pivot without rainbow pies.",
    `${unhide("Pivot Table | Slicers")} The tab is labelled PivotTable / Chart / Slicer. Insert → Chart from the pivot. One colour. Column or bar. No 3D pie.`,
    "Chart the summary, not 1,000 RawData rows. That is the WhatsApp to a partner.",
  ),
  pack(
    54,
    "Pivot Table | Slicers",
    "You can put a slicer on the pivot so a non-Sheets owner can poke East.",
    `${unhide("Pivot Table | Slicers")} Data → Slicer → Region, then Sales Person. Click East. Numbers drop. Reset. Do not leave three slicers on.`,
    "Slicer is how a non-Sheets owner uses the system. One click, read the number, reset.",
  ),
  pack(
    55,
    "Depended Drop Down",
    "You can build a short Google Form from the same lists as the sheet.",
    `${unhide("Depended Drop Down")} Forms → Use Case, Category, Subcategory as dropdowns from this tab. Qty as a number. Do not add 20 questions.`,
    "A form is a gate. Dropdowns from the same lists as the sheet. If qty is a paragraph, the sheet dies.",
  ),
  pack(
    56,
    "RawData",
    "You can land form answers on a tab you QUERY like RawData.",
    `${unhide("RawData")} Link a form to this workbook as a new tab FormIn. Do not pretty that tab. QUERY or FILTER it the way Query Basics reads RawData.`,
    "The form tab is raw. Same pattern as a dump → RawData. Format it heavily and the next response shifts columns.",
  ),
  pack(
    57,
    "CONCATENATE | TEXT_JOIN",
    "You can build To / Subject / Body columns for a mail merge.",
    `${unhide("CONCATENATE | TEXT_JOIN")} Three columns: To (dummy), Subject, Body using TEXTJOIN. That is Form Mule's merge sheet. Install the add-on only if they actually send mail.`,
    "Most of this class chases on WhatsApp. Form Mule is for a distributor who wants a proper mail. Merge from a filtered list, not 1,000 RawData rows.",
  ),
  pack(
    58,
    "Google Sheets Session",
    "A new form row can ping you without sitting on the file.",
    `${unhide("Google Sheets Session")} Tools → Notification rules → a new row is added on the form tab (or Data Clean Up as stand-in). Daily digest. Mark Status on the TOC when the session is done.`,
    "Last mile: data in, alarm out. If you notify on every RawData edit they will ignore you.",
  ),
];
