-- AlterEnum
ALTER TYPE "LeadSourceChannel" ADD VALUE IF NOT EXISTS 'INDIAMART';
ALTER TYPE "LeadSourceChannel" ADD VALUE IF NOT EXISTS 'TRADEINDIA';
ALTER TYPE "LeadSourceChannel" ADD VALUE IF NOT EXISTS 'SHOPIFY';
ALTER TYPE "LeadSourceChannel" ADD VALUE IF NOT EXISTS 'WOOCOMMERCE';
ALTER TYPE "LeadSourceChannel" ADD VALUE IF NOT EXISTS 'JUSTDIAL';
